name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        tag=$DOCKER_UN/gleam:$(date +%s)
        docker build . --file Dockerfile --tag $tag

        docker login -u $DOCKER_UN -p $DOCKER_PAT
        docker push $tag
      env:
        DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        DOCKER_UN: ${{ secrets.DOCKER_UN }}
